# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_preniumplan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_registdate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
