# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:28


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_mail', models.CharField(max_length=100, null=True)),
                ('company_url', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('company_legal_representative', models.CharField(max_length=30)),
                ('company_status', models.CharField(max_length=100)),
                ('company_field', models.CharField(max_length=20)),
                ('registered_capital', models.FloatField(max_length=100, null=True)),
                ('registered_time', models.DateTimeField(max_length=10, null=True)),
                ('company_type', models.CharField(max_length=30)),
                ('business_term', models.FloatField(null=True)),
                ('registered_organization', models.CharField(max_length=100)),
                ('uni_business_code', models.CharField(max_length=100)),
                ('business_scope', models.CharField(max_length=100)),
            ],
        ),
    ]
